namespace Game.Tiles
{
    public enum TileType {
        Tiles_0,
        Tiles_1,
        Tiles_2,
        Tiles_3,
        Tiles_4,
        Tiles_5,
        Tiles_6,
        Tiles_7,
        Tiles_8,
        Tiles_9,
        Tiles_10,
        Tiles_11,
        Tiles_12,
        Tiles_13,
        Tiles_14,
        Tiles_15,
        Tiles_16,
        Tiles_17,
        Tiles_18,
        Tiles_19,
        Tiles_20,
        Tiles_21,
        Tiles_22,
        Tiles_23,
    }
}